x-base_service: &base_service
  stop_signal: SIGINT
  restart: always
  tty: true
  stdin_open: true
  env_file: .env
  ipc: host

x-base_rust: &base_rust
  environment:
    RUST_LOG: $RUST_LOG

x-base_service_wikidex: &base_wikidex
  ports:
    - "${WIKIDEX_HOST_PORT}:${WIKIDEX_CONT_PORT}"
  volumes:
    - ../../../wikidex/prompt:/prompt
  build:
    dockerfile: Dockerfile
    context: ../../../wikidex
    args:
      DATABASE_URL: postgres://postgres:postgres@192.168.1.120:5433/postgres

services:
  wikidex-vllm:
    <<:
      - *base_service
      - *base_wikidex
      - *base_rust
    profiles:
      - wikidex-local
    entrypoint:
      [
        wikidex,
        server,
        --api-key,
        "$API_SECRET_KEY",
        --docstore-url,
        "$DOCSTORE_URL",
        --redis-url,
        "$REDIS_URL",
        --host,
        0.0.0.0,
        --port,
        "$WIKIDEX_CONT_PORT",
        --system-prompt-path,
        "$SYSTEM_PROMPT_PATH",
        --index-url,
        "$INDEX_URL",
        --embed-name,
        "$SBERT_MODEL_NAME",
        --embed-url,
        "$EMBED_URL",
        --embed-endpoint,
        openai,
        --llm-name,
        "$LLM_MODEL_NAME",
        --llm-url,
        "$VLLM_URL",
        --llm-endpoint,
        openai,
        --llm-kind,
        "$MODEL_KIND",
      ]
    depends_on:
      - postgres

  wikidex-trt:
    <<:
      - *base_service
      - *base_wikidex
      - *base_rust
    profiles:
      - wikidex
    build:
      dockerfile: Dockerfile
      context: ../../../wikidex
    entrypoint:
      [
        wikidex,
        server,
        --api-key,
        "$API_SECRET_KEY",
        --docstore-url,
        "$DOCSTORE_URL",
        --redis-url,
        "$REDIS_URL",
        --host,
        0.0.0.0,
        --port,
        "$WIKIDEX_CONT_PORT",
        --system-prompt-path,
        "$SYSTEM_PROMPT_PATH",
        --index-url,
        "$INDEX_URL",
        --embed-name,
        "$SBERT_MODEL_NAME",
        --embed-url,
        "$EMBED_URL",
        --embed-endpoint,
        openai,
        --llm-name,
        "$LLM_MODEL_NAME",
        --llm-url,
        "$TRITON_GRPC_URL",
        --llm-endpoint,
        triton,
        --llm-kind,
        "$MODEL_KIND",
      ]
    depends_on:
      - postgres
      - triton
