FROM vllm/vllm-openai:latest

# Install Git LFS
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked,rw apt-get update && \
    apt-get install --no-install-recommends -y git-lfs python3 && \
    rm -rf /var/lib/apt/lists/*

ARG LLM_MODEL_NAME
ENV MODEL_REPO=https://huggingface.co/$LLM_MODEL_NAME
ENV MODEL_PATH=/root/.cache/git/$LLM_MODEL_NAME

# Clone the model
RUN --mount=type=cache,target=/root/.cache/git,rw \
    if ! cd $MODEL_PATH; then (git lfs install; git clone $MODEL_REPO $MODEL_PATH); fi

# Copy model to a specific directory
RUN mkdir -p $LLM_MODEL_NAME
RUN --mount=type=cache,target=/root/.cache/git,rw \
    cp -R $MODEL_PATH/* $LLM_MODEL_NAME 

ENTRYPOINT python3 -m vllm.entrypoints.openai.api_server \
    --disable-log-stats \
    --disable-log-requests \
    --gpu-memory-utilization 0.85 \
    --model $LLM_MODEL_NAME \
    --host 0.0.0.0 \
    --port $VLLM_CONT_PORT \
    --dtype half \
    --max-model-len $MAX_MODEL_LEN

