# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

variables:
  DATABASE_URL: "sqlite://sqlite_dummy.db"

#   KUBERNETES_CPU_REQUEST: 400m
#   KUBERNETES_CPU_LIMIT: 12000m
#   KUBERNETES_MEMORY_REQUEST: 2Gi
#   KUBERNETES_MEMORY_LIMIT: 8Gi

stages:
  - sast
  - check
  - check-isolation
  - build-isolation
  - test

sast:
  stage: sast
include:
  - template: Security/SAST.gitlab-ci.yml

Check Everything - PostgreSQL:
  cache:
    key: binaries-cache
    paths:
      - wikidex/target/*
  image: rust:latest
  stage: check
  script:
    - apt-get update
    - apt-get install -y cmake pkg-config libssl-dev liblapack-dev libblas-dev
    - cd wikidex
    - cargo check --no-default-features --features ingest,server,sqlite

Check Server + SQLite:
  cache:
    key: binaries-cache
    paths:
      - wikidex/target/*
  image: rust:latest
  stage: check-isolation
  script:
    - apt-get update
    - apt-get install -y cmake pkg-config libssl-dev liblapack-dev libblas-dev
    - cd wikidex
    - cargo check --no-default-features --features server,sqlite

Check Ingest + SQLite:
  cache:
    key: binaries-cache
    paths:
      - wikidex/target/*
  image: rust:latest
  stage: check-isolation
  script:
    - apt-get update
    - apt-get install -y cmake pkg-config libssl-dev liblapack-dev libblas-dev
    - cd wikidex
    - cargo check --no-default-features --features ingest,sqlite

Build Server + SQLite:
  cache:
    key: binaries-cache
    paths:
      - wikidex/target/*
  image: rust:latest
  stage: build-isolation
  script:
    - apt-get update
    - apt-get install -y cmake pkg-config libssl-dev liblapack-dev libblas-dev
    - cd wikidex
    - cargo build --no-default-features --features server,sqlite

Build Ingest + SQLite:
  cache:
    key: binaries-cache
    paths:
      - wikidex/target/*
  image: rust:latest
  stage: build-isolation
  script:
    - apt-get update
    - apt-get install -y cmake pkg-config libssl-dev liblapack-dev libblas-dev
    - cd wikidex
    - cargo build --no-default-features --features ingest,sqlite

Test Everything:
  cache:
    key: binaries-cache
    paths:
      - wikidex/target/*
  image: rust:latest
  stage: test
  script:
    - apt-get update
    - apt-get install -y cmake pkg-config libssl-dev liblapack-dev libblas-dev
    - cd wikidex
    - cargo test --package wikidex --bin wikidex --no-default-features --features sqlite,server,ingest -- --exact --show-output  --nocapture
