variables:
  KUBERNETES_CPU_REQUEST: 400m
  KUBERNETES_CPU_LIMIT: 12000m
  KUBERNETES_MEMORY_REQUEST: 2Gi
  KUBERNETES_MEMORY_LIMIT: 8Gi
  FF_USE_FASTZIP: "true"
  # These can be specified per job or per pipeline (slowest, slow, default, fast, and fastest)
  ARTIFACT_COMPRESSION_LEVEL: "fastest"
  CACHE_COMPRESSION_LEVEL: "fastest"

stages:
  - All
sast:
  stage: All
include:
  - template: Security/SAST.gitlab-ci.yml

Audit:
  cache: []
  image: registry.semanticallyinvalid.net/omnipedia/cicd/wikidex-cicd:latest
  stage: All
  allow_failure:
    exit_codes:
      - 1
  script:
    - cd wikidex
    - cargo audit

SQLite Server:
  variables:
    DATABASE_URL: sqlite://sqlite_dummy.db
  cache:
    - key: cache-sqlite-server
      paths:
        - wikidex/target/*
  image: registry.semanticallyinvalid.net/omnipedia/cicd/wikidex-cicd:latest
  stage: All
  script:
    - cd wikidex
    - cargo build --no-default-features --features sqlite,server

SQLite Ingest:
  variables:
    DATABASE_URL: sqlite://sqlite_dummy.db
  cache:
    - key: cache-sqlite-ingest
      paths:
        - wikidex/target/*
  image: registry.semanticallyinvalid.net/omnipedia/cicd/wikidex-cicd:latest
  stage: All
  script:
    - cd wikidex
    - cargo build --no-default-features --features sqlite,ingest

SQLite Ingest Server:
  variables:
    DATABASE_URL: sqlite://sqlite_dummy.db
  cache:
    - key: cache-sqlite-ingest-server
      paths:
        - wikidex/target/*
  image: registry.semanticallyinvalid.net/omnipedia/cicd/wikidex-cicd:latest
  stage: All
  script:
    - cd wikidex
    - cargo build --no-default-features --features sqlite,ingest,server

SQLite Test:
  variables:
    DATABASE_URL: sqlite://sqlite_dummy.db
  cache:
    - key: cache-sqlite-ingest-server-test
      paths:
        - wikidex/target/*
  image: registry.semanticallyinvalid.net/omnipedia/cicd/wikidex-cicd:latest
  stage: All
  script:
    - cd wikidex
    - cargo test --package wikidex --bin wikidex --no-default-features --features sqlite,server,ingest -- --exact --show-output  --nocapture

PostgreSQL:
  variables:
    DATABASE_URL: postgres://wikidex:wikidex@wikidex-dummy-wikidex-dev-postgresql.wikidex-dev:5432/wikipedia
  cache:
    - key: cache-postgres-all-debug
      paths:
        - wikidex/target/debug/*
        - wikidex/target/.rustc_info.json
        - wikidex/target/CACHEDIR.TAG
  image: registry.semanticallyinvalid.net/omnipedia/cicd/wikidex-cicd:latest
  stage: All
  script:
    - cd wikidex
    - cargo build --no-default-features --features server,postgres
