# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

variables:
  DATABASE_URL: "sqlite://sqlite_dummy.db"
  KUBERNETES_CPU_REQUEST: 400m
  KUBERNETES_CPU_LIMIT: 12000m
  KUBERNETES_MEMORY_REQUEST: 2Gi
  KUBERNETES_MEMORY_LIMIT: 8Gi

stages:
  - check
  - test
  # - sast

# sast:
#   stage: sast
# include:
#   - template: Security/SAST.gitlab-ci.yml

ingest check:
  image: rust:latest
  stage: check
  script:
    - apt-get update
    - apt-get install -y cmake pkg-config libssl-dev liblapack-dev libblas-dev
    - cd rust
    - cargo check
    - cargo check --no-default-features --features ingest
server check:
  image: rust:latest
  stage: check
  script:
    - apt-get update
    - apt-get install -y cmake pkg-config libssl-dev liblapack-dev libblas-dev
    - cd rust
    - cargo check
    - cargo check --no-default-features --features server
breeder check:
  image: rust:latest
  stage: check
  script:
    - apt-get update
    - apt-get install -y cmake pkg-config libssl-dev liblapack-dev libblas-dev
    - cd rust
    - cargo check
    - cargo check --no-default-features --features breeder

test-breeder:
  image: rust:latest
  stage: test
  script:
    - apt-get update
    - apt-get install -y cmake pkg-config libssl-dev liblapack-dev libblas-dev
    - cd rust
    - "cargo test --package omnipedia --bin omnipedia --no-default-features --features breeder -- breeder::operator::"
