variables:
  APT_COMMON: cmake pkg-config libssl-dev liblapack-dev libblas-dev protobuf-compiler
  KUBERNETES_CPU_REQUEST: 400m
  KUBERNETES_CPU_LIMIT: 12000m
  KUBERNETES_MEMORY_REQUEST: 2Gi
  KUBERNETES_MEMORY_LIMIT: 8Gi

stages:
  - Sast
  - All
  - Isolation
  - Test
sast:
  stage: Sast
include:
  - template: Security/SAST.gitlab-ci.yml

Audit Everything:
  cache: []
  image: registry.semanticallyinvalid.net/omnipedia/cicd/wikidex-cicd:latest
  stage: Sast
  allow_failure:
    exit_codes:
      - 1
  script:
    - cd wikidex
    - cargo audit

Build Server + Ingest + SQLite:
  variables:
    DATABASE_URL: sqlite://sqlite_dummy.db
  cache:
    - key: cache-sqlite-$CI_COMMIT_REF_SLUG
      paths:
        - wikidex/target/*
  image: registry.semanticallyinvalid.net/omnipedia/cicd/wikidex-cicd:latest
  stage: All
  script:
    - cd wikidex
    - cargo build --no-default-features --features sqlite,ingest,server

Build Server + Ingest + PostgreSQL:
  variables:
    DATABASE_URL: postgres://wikidex:wikidex@wikidex-dummy-wikidex-dev-postgresql.wikidex-dev:5432/wikipedia
  cache:
    - key: cache-postgres-$CI_COMMIT_REF_SLUG
      paths:
        - wikidex/target/*
  image: registry.semanticallyinvalid.net/omnipedia/cicd/wikidex-cicd:latest
  stage: All
  script:
    - cd wikidex
    - cargo build --no-default-features --features postgres,ingest,server

Build Server + SQLite:
  variables:
    DATABASE_URL: sqlite://sqlite_dummy.db
  cache:
    - key: cache-sqlite-$CI_COMMIT_REF_SLUG
      paths:
        - wikidex/target/*
  image: registry.semanticallyinvalid.net/omnipedia/cicd/wikidex-cicd:latest
  stage: Isolation
  script:
    - cd wikidex
    - cargo build --no-default-features --features server,sqlite

Build Ingest + SQLite:
  variables:
    DATABASE_URL: sqlite://sqlite_dummy.db
  cache:
    - key: cache-sqlite-$CI_COMMIT_REF_SLUG
      paths:
        - wikidex/target/*
  image: registry.semanticallyinvalid.net/omnipedia/cicd/wikidex-cicd:latest
  stage: Isolation
  script:
    - cd wikidex
    - cargo build --no-default-features --features ingest,sqlite

Build Server + PostgreSQL:
  variables:
    DATABASE_URL: postgres://wikidex:wikidex@wikidex-dummy-wikidex-dev-postgresql.wikidex-dev:5432/wikipedia
  cache:
    - key: cache-postgres-$CI_COMMIT_REF_SLUG
      paths:
        - wikidex/target/*
  image: registry.semanticallyinvalid.net/omnipedia/cicd/wikidex-cicd:latest
  stage: Isolation
  script:
    - cd wikidex
    - cargo build --no-default-features --features server,postgres

Test Everything:
  variables:
    DATABASE_URL: sqlite://sqlite_dummy.db
  cache:
    - key: cache-sqlite-$CI_COMMIT_REF_SLUG
      paths:
        - wikidex/target/*
  image: registry.semanticallyinvalid.net/omnipedia/cicd/wikidex-cicd:latest
  stage: Test
  script:
    - cd wikidex
    - cargo test --package wikidex --bin wikidex --no-default-features --features sqlite,server,ingest -- --exact --show-output  --nocapture
