variables:
  APT_COMMON: cmake pkg-config libssl-dev liblapack-dev libblas-dev protobuf-compiler
  KUBERNETES_CPU_REQUEST: 400m
  KUBERNETES_CPU_LIMIT: 12000m
  KUBERNETES_MEMORY_REQUEST: 2Gi
  KUBERNETES_MEMORY_LIMIT: 8Gi

stages:
  - Cache
  - Sast
  - Build
  - Test

sast:
  stage: Sast
include:
  - template: Security/SAST.gitlab-ci.yml

Populate Cache:
  cache:
    - key: binaries-cache
      paths:
        - wikidex/target/*
    - key: apt-cache
      paths:
        - ~/.cache/apt/*
    - key: cargo-registry
      paths:
        - ~/.cargo/registry/*
  image: rust:latest
  stage: Cache
  script:
    - apt-get update
    - apt-get install -y $APT_COMMON cargo
    - cargo install cargo-audit
    - cd wikidex
    - cargo fetch

Audit Everything:
  cache:
    - key: binaries-cache
      paths:
        - wikidex/target/*
    - key: apt-cache
      paths:
        - ~/.cache/apt/*
    - key: cargo-registry
      paths:
        - ~/.cargo/registry/*
  image: rust:latest
  stage: Sast
  allow_failure:
    exit_codes:
      - 1
  script:
    - apt-get update
    - apt-get install -y $APT_COMMON cargo
    - cargo install cargo-audit
    - cd wikidex
    - cargo audit

Build Server + SQLite:
  variables:
    DATABASE_URL: sqlite://sqlite_dummy.db
  cache:
    - key: binaries-cache
      paths:
        - wikidex/target/*
    - key: apt-cache
      paths:
        - ~/.cache/apt/*
    - key: cargo-registry
      paths:
        - ~/.cargo/registry/*
  image: rust:latest
  stage: Build
  script:
    - apt-get update
    - apt-get install -y $APT_COMMON
    - cd wikidex
    - cargo build --no-default-features --features server,sqlite

Build Ingest + SQLite:
  variables:
    DATABASE_URL: sqlite://sqlite_dummy.db
  cache:
    - key: binaries-cache
      paths:
        - wikidex/target/*
    - key: apt-cache
      paths:
        - ~/.cache/apt/*
    - key: cargo-registry
      paths:
        - ~/.cargo/registry/*
  image: rust:latest
  stage: Build
  script:
    - apt-get update
    - apt-get install -y $APT_COMMON
    - cd wikidex
    - cargo build --no-default-features --features ingest,sqlite

Build Server + PostgreSQL:
  variables:
    DATABASE_URL: postgres://wikidex:wikidex@wikidex-dummy-wikidex-dev-postgresql.wikidex-dev:5432/wikipedia
  cache:
    - key: binaries-cache
      paths:
        - wikidex/target/*
    - key: apt-cache
      paths:
        - ~/.cache/apt/*
    - key: cargo-registry
      paths:
        - ~/.cargo/registry/*
  image: rust:latest
  stage: Build
  script:
    - apt-get update
    - apt-get install -y $APT_COMMON
    - cd wikidex
    - cargo build --no-default-features --features server,postgres

Test Everything:
  variables:
    DATABASE_URL: sqlite://sqlite_dummy.db
  cache:
    - key: binaries-cache
      paths:
        - wikidex/target/*
    - key: apt-cache
      paths:
        - ~/.cache/apt/*
    - key: cargo-registry
      paths:
        - ~/.cargo/registry/*
  image: rust:latest
  stage: Test
  script:
    - apt-get update
    - apt-get install -y $APT_COMMON
    - cd wikidex
    - cargo test --package wikidex --bin wikidex --no-default-features --features sqlite,server,ingest -- --exact --show-output  --nocapture
