# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

variables:
  KUBERNETES_CPU_REQUEST: 400m
  KUBERNETES_CPU_LIMIT: 12000m
  KUBERNETES_MEMORY_REQUEST: 2Gi
  KUBERNETES_MEMORY_LIMIT: 8Gi
  DATABASE_URL: "sqlite://sqlite_dummy.db"

stages:
  - build
  - check
  - test

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml

build:
  cache:
    key: binaries-cache
    paths:
      - rust/target/*
  image: rust:latest
  stage: build
  script:
    - apt-get update
    - apt-get install -y cmake pkg-config libssl-dev liblapack-dev libblas-dev
    - cd rust
    - cargo check

ingest:
  cache:
    key: binaries-cache
    paths:
      - rust/target/*
  image: rust:latest
  stage: check
  script:
    - apt-get update
    - apt-get install -y cmake pkg-config libssl-dev liblapack-dev libblas-dev
    - cd rust
    - cargo check --no-default-features --features ingest

server:
  cache:
    key: binaries-cache
    paths:
      - rust/target/*
  image: rust:latest
  stage: check
  script:
    - apt-get update
    - apt-get install -y cmake pkg-config libssl-dev liblapack-dev libblas-dev
    - cd rust
    - cargo check --no-default-features --features server

breeder:
  cache:
    key: binaries-cache
    paths:
      - rust/target/*
  image: rust:latest
  stage: check
  script:
    - apt-get update
    - apt-get install -y cmake pkg-config libssl-dev liblapack-dev libblas-dev
    - cd rust
    - cargo check --no-default-features --features breeder

test:
  cache:
    key: binaries-cache
    paths:
      - rust/target/*
  image: rust:latest
  stage: test
  script:
    - apt-get update
    - apt-get install -y cmake pkg-config libssl-dev liblapack-dev libblas-dev
    - cd rust
    - "cargo test --package omnipedia --bin omnipedia --no-default-features --features breeder -- breeder::operator::"
