x-base_service: &base_service
  stop_signal: SIGINT
  restart: always
  tty: true
  stdin_open: true
  env_file: .env
  ipc: host

services:
  haproxy:
    <<:
      - *base_service
    profiles:
      - index
      - server
    image: haproxy:latest
    ports:
      - "$INDEX_HAPROXY_PORT:$INDEX_HAPROXY_PORT"
    volumes:
      - ../../../haproxy:/usr/local/etc/haproxy/
    # entrypoint: [haproxy, -c, -V, -f, /usr/local/etc/haproxy/haproxy.cfg]
