x-base_service: &base_service
  stop_signal: SIGINT
  restart: always
  tty: true
  stdin_open: true
  env_file: .env
  ipc: host

x-base_service_nvidia: &base_service_nvidia
  <<: *base_service
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            device_ids: ["0"]
            capabilities: [gpu]

x-base_service_index: &base_index
  ports:
    - "${INDEX_HOST_PORT_BEGIN}-${INDEX_HOST_PORT_END}:${INDEX_CONT_PORT}"
  volumes:
    - ~/Documents/WIKIDUMPS/${EXTRACT_DATE}/index/thenlper/gte-small:/db
x-base_rust: &base_rust
  environment:
    RUST_LOG: $RUST_LOG

services:
  index:
    <<:
      - *base_service
      - *base_index
      - *base_rust
    profiles:
      - server
      - index
    build: https://github.com/MichaelMcCulloch/face.git#0.1.1
    entrypoint: [face, --index-path, $INDEX_PATH]
    deploy:
      mode: replicated
      replicas: 1
