CREATE TABLE IF NOT EXISTS completed_on (
  db_date INTEGER NOT NULL, article_count INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS wiki_markup (
  id INTEGER PRIMARY KEY NOT NULL, title TEXT NOT NULL, 
  text BLOB NOT NULL, access_date INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS article (
  id INTEGER PRIMARY KEY NOT NULL, title TEXT NOT NULL, 
  access_date INTEGER NOT NULL, modification_date INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS document (
  id INTEGER PRIMARY KEY NOT NULL, 
  text BLOB NOT NULL, 
  article INTEGER NOT NULL, 
  FOREIGN KEY(article) REFERENCES article(id)
);
CREATE TABLE IF NOT EXISTS embeddings (
  id INTEGER PRIMARY KEY NOT NULL, gte_small BLOB NOT NULL
);
