/*
 * face
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Neighbors {
    #[serde(rename = "neighbors")]
    pub neighbors: Vec<i64>,
}

impl Neighbors {
    pub fn new(neighbors: Vec<i64>) -> Neighbors {
        Neighbors {
            neighbors,
        }
    }
}

