/*
 * face
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Query {
    #[serde(rename = "count")]
    pub count: i32,
    #[serde(rename = "embedding")]
    pub embedding: Vec<f32>,
}

impl Query {
    pub fn new(count: i32, embedding: Vec<f32>) -> Query {
        Query {
            count,
            embedding,
        }
    }
}

