FROM michaelf34/infinity:latest

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked,rw apt-get update && \
    apt-get install --no-install-recommends -y git git-lfs && \
    rm -rf /var/lib/apt/lists/*

ARG TORCH_CUDA_ARCH_LIST
ARG SBERT_MODEL_NAME

ENV MODEL_REPO=https://huggingface.co/$SBERT_MODEL_NAME
ENV MODEL_PATH=/root/.cache/git/$SBERT_MODEL_NAME

# RUN git lfs install
# RUN git clone $MODEL_REPO $MODEL_PATH

RUN --mount=type=cache,target=/root/.cache/git,rw \
    if ! cd $MODEL_PATH; then (git lfs install; git clone $MODEL_REPO $MODEL_PATH); fi

RUN mkdir -p /$SBERT_MODEL_NAME

RUN --mount=type=cache,target=/root/.cache/git,rw \
    cp -R $MODEL_PATH/* /$SBERT_MODEL_NAME 


ENTRYPOINT  infinity_emb --model-name-or-path /$SBERT_MODEL_NAME --port $EMBED_CONT_PORT --device cuda --batch-size 64
# ENTRYPOINT  infinity_emb --help