[engine]
protocol = "http"
host = "omnipedia"
port = 5000
index = "/db/thenlper/gte-small/index_pca64_flat.faiss"
docstore = "/db/thenlper/gte-small/docstore.sqlitedb"
conversation_path = "conversation"
query_path = "query"

[embed]
protocol = "http"
host = "embeddings"
port = 9000
model = "thenlper/gte-small"
batch_size = 640
path = "embed"

[llm]
protocol = "http"
host = "vllm"
port = 5050
model = "TheBloke/zephyr-7B-beta-AWQ"

[ui]
protocol = "http"
host = "ui"
port = 3000
