x-base_service: &base_service
  stop_signal: SIGINT
  restart: always
  tty: true
  stdin_open: true
  env_file: .env
  ipc: host

x-base_service_postgres: &base_postgres
  image: postgres
  shm_size: 1gb

x-base_service_postgres_prod: &base_postgres_prod
  <<:
    - *base_postgres
  volumes:
    - ~/ContainerData/PostgreSQL/wikidex/${EXTRACT_DATE}:/var/lib/postgresql/data
  ports:
    - $POSTGRES_PORT:$POSTGRES_PORT

x-base_service_postgres_dummy: &base_postgres_dummy
  <<:
    - *base_postgres
  volumes:
    - ~/ContainerData/PostgreSQL/wikidex/dummy/:/var/lib/postgresql/data
  ports:
    - $POSTGRES_DUMMY_PORT:$POSTGRES_PORT

x-base_service_postgres_prod_gid: &base_postgres_prod_gid_fix
  <<:
    - *base_postgres_prod
  user: 1000:1000

x-base_service_postgres_dummy_gid: &base_postgres_dummy_gid_fix
  <<:
    - *base_postgres_dummy
  user: 1000:1000

services:
  postgres:
    profiles:
      - server
    <<:
      - *base_service
      - *base_postgres_prod_gid_fix

  postgres_dummy:
    profiles:
      - dummy
    <<:
      - *base_service
      - *base_postgres_dummy_gid_fix
